#!/usr/bin/env ruby
# Look up the youdao dictionary
# http://dict.youdao.com

require 'rubygems'
require 'open-uri'
require 'nokogiri'

# hello is the word to search
if ARGV.size < 1
  puts "Please provide the word to look up.\n Usage: kkdict word_to_look_up"
else
  puts '*** Searching host...'
  url = "http://dict.youdao.com/search?le=eng&q=#{ARGV[0]}&tab=chn&keyfrom=dict.top"
  page = Nokogiri::HTML(open(url))
  page.xpath('//*[@id="phrsListTab"]//div[@class="trans-container"]/ul/li').each do |inner_li|
    puts inner_li.inner_html
  end

end

puts '*' * 15
puts 'Send feedback to: Liang Tang <liang.xjtu (at) gmail.com>'
